sudo: false

cache:
  directories:
    - elm-stuff/build-artifacts

env:
  matrix:
    - TARGET_NODE_VERSION=node

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm@0.18.0 elm-format@exp create-elm-app@1.5.0
  - travis_retry elm-package install --yes

script:
  - elm-format --validate src
  - elm-app build
